require('dotenv').config();
const express=require('express'),path=require('path'),bcrypt=require('bcryptjs'),session=require('express-session'),{Pool}=require('pg');
const app=express(),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false});
// Render runs behind a reverse proxy. Trust it so secure session cookies are set correctly.
app.set('trust proxy',1);
app.use(express.json());app.use(session({secret:process.env.SESSION_SECRET||'dev-change-this',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000}}));app.use(express.static(path.join(__dirname,'public')));
const pub=r=>({id:r.id,name:r.name,email:r.email,xp:r.xp,streak:r.streak||1,completed:r.completed||[]});
async function init(){
  await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,xp INT NOT NULL DEFAULT 0,streak INT NOT NULL DEFAULT 1,last_active DATE,completed JSONB NOT NULL DEFAULT '[]'::jsonb,created_at TIMESTAMPTZ DEFAULT NOW())`);
  await pool.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS certificate_issued_at TIMESTAMPTZ');
  await pool.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS certificate_code TEXT UNIQUE');
  await pool.query(`CREATE TABLE IF NOT EXISTS xp_events(user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,event_key TEXT NOT NULL,amount INT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(user_id,event_key))`);
  let e=await pool.query('SELECT id FROM users WHERE email=$1',['student@cyberquest.demo']);
  if(!e.rowCount){let h=await bcrypt.hash('CyberQuest123',12);await pool.query('INSERT INTO users(name,email,password_hash,last_active) VALUES($1,$2,$3,CURRENT_DATE)',['Demo Student','student@cyberquest.demo',h])}
}
async function auth(req,res,next){if(!req.session.userId)return res.status(401).json({error:'Not signed in'});let r=await pool.query('SELECT * FROM users WHERE id=$1',[req.session.userId]);if(!r.rowCount)return res.status(401).json({error:'Session expired'});req.user=r.rows[0];next()}
app.post('/api/register',async(req,res)=>{try{let name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(name.length<2)return res.status(400).json({error:'Enter your name.'});if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return res.status(400).json({error:'Enter a valid email.'});if(password.length<6)return res.status(400).json({error:'Password must be at least 6 characters.'});let h=await bcrypt.hash(password,12),r=await pool.query('INSERT INTO users(name,email,password_hash,last_active) VALUES($1,$2,$3,CURRENT_DATE) RETURNING *',[name,email,h]);req.session.userId=r.rows[0].id;res.json({user:pub(r.rows[0]),progress:pub(r.rows[0])})}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'An account with that email already exists.':'Could not create account.'})}});
app.post('/api/login',async(req,res)=>{try{let email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),r=await pool.query('SELECT * FROM users WHERE email=$1',[email]);if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash)))return res.status(401).json({error:'Incorrect email or password.'});let u=r.rows[0],today=new Date(),last=u.last_active?new Date(u.last_active):null;if(last){let d=Math.floor((Date.UTC(today.getFullYear(),today.getMonth(),today.getDate())-Date.UTC(last.getFullYear(),last.getMonth(),last.getDate()))/86400000);u.streak=d===1?u.streak+1:d>1?1:u.streak}else u.streak=1;await pool.query('UPDATE users SET streak=$1,last_active=CURRENT_DATE WHERE id=$2',[u.streak,u.id]);req.session.userId=u.id;res.json({user:pub(u),progress:pub(u)})}catch(e){res.status(500).json({error:'Login failed.'})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',async(req,res)=>{if(!req.session.userId)return res.status(401).json({error:'Not signed in'});let r=await pool.query('SELECT * FROM users WHERE id=$1',[req.session.userId]);if(!r.rowCount)return res.status(401).json({error:'Not signed in'});res.json({user:pub(r.rows[0]),progress:pub(r.rows[0])})});
app.post('/api/progress',auth,async(req,res)=>{
  const amount=Math.max(0,Math.min(100,Number(req.body.xp)||0));
  const key=String(req.body.key||'').trim();
  if(amount<=0)return res.status(400).json({error:'XP amount must be greater than 0.'});
  const c=Array.isArray(req.user.completed)?req.user.completed:[];
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    let awarded=false;
    if(key){
      if(!c.includes(key)){
        const event=await client.query('INSERT INTO xp_events(user_id,event_key,amount) VALUES($1,$2,$3) ON CONFLICT(user_id,event_key) DO NOTHING RETURNING event_key',[req.user.id,key,amount]);
        if(event.rowCount){c.push(key);await client.query('UPDATE users SET xp=xp+$1,completed=$2 WHERE id=$3',[amount,JSON.stringify(c),req.user.id]);awarded=true;}
      }
    }else{
      await client.query('UPDATE users SET xp=xp+$1 WHERE id=$2',[amount,req.user.id]);
      awarded=true;
    }
    await client.query('COMMIT');
    const r=await pool.query('SELECT * FROM users WHERE id=$1',[req.user.id]);
    res.json({progress:pub(r.rows[0]),awarded,xpAwarded:awarded?amount:0});
  }catch(e){await client.query('ROLLBACK');console.error('Progress save failed:',e);res.status(500).json({error:'Could not save XP. Please try again.'})}
  finally{client.release()}
});
app.get('/api/certificate',auth,async(req,res)=>{try{let completed=Array.isArray(req.user.completed)?req.user.completed:[],completedZones=Array.from({length:12},(_,i)=>completed.includes('lesson-'+i)).filter(Boolean).length,r=await pool.query('SELECT certificate_issued_at,certificate_code FROM users WHERE id=$1',[req.user.id]),row=r.rows[0];res.json({eligible:completedZones===12,completedZones,issuedAt:row.certificate_issued_at,code:row.certificate_code})}catch(e){res.status(500).json({error:'Could not load certificate.'})}});
app.post('/api/certificate',auth,async(req,res)=>{try{let completed=Array.isArray(req.user.completed)?req.user.completed:[],completedZones=Array.from({length:12},(_,i)=>completed.includes('lesson-'+i)).filter(Boolean).length;if(completedZones<12)return res.status(403).json({error:`Complete all 12 learning zones first. You have completed ${completedZones}/12.`});let existing=await pool.query('SELECT certificate_issued_at,certificate_code FROM users WHERE id=$1',[req.user.id]);if(existing.rows[0].certificate_issued_at)return res.json({issuedAt:existing.rows[0].certificate_issued_at,code:existing.rows[0].certificate_code});let code='CQ-'+Math.random().toString(36).slice(2,8).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase(),r=await pool.query('UPDATE users SET certificate_issued_at=NOW(),certificate_code=$1 WHERE id=$2 RETURNING certificate_issued_at,certificate_code',[code,req.user.id]);res.json({issuedAt:r.rows[0].certificate_issued_at,code:r.rows[0].certificate_code})}catch(e){res.status(500).json({error:'Could not issue certificate.'})}});
app.get('/api/leaderboard',async(req,res)=>{let r=await pool.query('SELECT id,name,xp FROM users ORDER BY xp DESC,created_at ASC LIMIT 20');res.json({students:r.rows})});
app.get('/api/analytics',auth,async(req,res)=>{try{const c=Array.isArray(req.user.completed)?req.user.completed:[];const dailyRows=await pool.query(`SELECT d::date AS day,COALESCE(SUM(x.amount),0)::int AS xp,COUNT(x.event_key)::int AS events FROM generate_series(CURRENT_DATE-INTERVAL '13 days',CURRENT_DATE,INTERVAL '1 day') d LEFT JOIN xp_events x ON x.user_id=$1 AND x.created_at::date=d::date GROUP BY d::date ORDER BY d::date`,[req.user.id]);const daily=dailyRows.rows.map(r=>({label:new Date(r.day).toLocaleDateString(undefined,{month:'short',day:'numeric'}),xp:Number(r.xp)||0,events:Number(r.events)||0}));const weekXp=daily.slice(-7).reduce((n,x)=>n+x.xp,0);const prevWeekXp=daily.slice(0,7).reduce((n,x)=>n+x.xp,0);const events7=daily.slice(-7).reduce((n,x)=>n+x.events,0);const activeDays7=daily.slice(-7).filter(x=>x.events>0).length;const weekDelta=prevWeekXp?Math.round((weekXp-prevWeekXp)/prevWeekXp*100):weekXp?100:0;const lessons=c.filter(x=>x.startsWith('lesson-')).length,sessions=c.filter(x=>x.startsWith('session-')).length,labs=c.filter(x=>x.startsWith('advanced-')).length;const completedTotal=lessons+sessions+labs;const overall=Math.round((lessons/12+sessions/12+labs/6)/3*100);const eventCount=await pool.query('SELECT COUNT(*)::int AS n FROM xp_events WHERE user_id=$1',[req.user.id]);const activity=[{label:'Learning Zones',count:lessons,icon:'📚'},{label:'Cyber Sessions',count:sessions,icon:'◫'},{label:'Advanced Labs',count:labs,icon:'⌬'},{label:'XP Events',count:eventCount.rows[0].n,icon:'⚡'}];let momentumText='Keep learning to build your first performance trend.';if(weekXp>prevWeekXp)momentumText=`Your XP momentum is up ${weekDelta}% versus the previous 7-day period.`;else if(weekXp<prevWeekXp)momentumText=`Your recent XP momentum is ${Math.abs(weekDelta)}% lower than the previous 7-day period. A focused session can restart the trend.`;else if(weekXp)momentumText='Your XP momentum is steady. Keep completing focused activities to improve the trend.';res.json({xpTotal:req.user.xp,weekXp,prevWeekXp,weekDelta,events7,activeDays7,daily,completion:{lessons,sessions,labs},completedTotal,overall,activity,momentumText})}catch(e){console.error('Analytics error:',e);res.status(500).json({error:'Could not load student analytics.'})}});

app.get('/api/intelligence',auth,async(req,res)=>{try{const c=Array.isArray(req.user.completed)?req.user.completed:[];const lessonMap={"Phishing Awareness":[0,1],"Network Defense":[2,6],"Cryptography":[5],"SOC & Incident Response":[6,11],"Digital Forensics":[10],"Web Security":[8],"Identity & Access":[3],"Malware Defense":[4]};const labMap={"Phishing Awareness":['advanced-phishing-investigation'],"SOC & Incident Response":['advanced-soc-incident-response'],"Malware Defense":['advanced-ransomware-response'],"Network Defense":['advanced-network-attack-investigation'],"Digital Forensics":['advanced-digital-forensics-case'],"Web Security":['advanced-web-security-lab']};const skills=Object.entries(lessonMap).map(([name,idxs])=>{let lessonScore=Math.round(idxs.reduce((n,i)=>n+(c.includes('lesson-'+i)?1:0),0)/idxs.length*55);let sessionScore=Math.round(idxs.reduce((n,i)=>n+(c.includes('session-'+i)?1:0),0)/idxs.length*25);let labs=labMap[name]||[];let labScore=labs.length?Math.round(labs.reduce((n,k)=>n+(c.includes(k)?1:0),0)/labs.length*20):0;return {name,score:Math.min(100,lessonScore+sessionScore+labScore)}});skills.sort((a,b)=>a.score-b.score);const weakest=skills[0],strongest=[...skills].sort((a,b)=>b.score-a.score)[0];const recommendation=weakest.score<50?`Strengthen ${weakest.name} with a focused session and its advanced lab.`:weakest.score<80?`Practice ${weakest.name} next to move toward mastery.`:`Try an advanced challenge in ${strongest.name}.`;res.json({overall:Math.round(skills.reduce((n,s)=>n+s.score,0)/skills.length),skills,weakest,strongest,recommendation,signals:{lessons:c.filter(x=>x.startsWith('lesson-')).length,sessions:c.filter(x=>x.startsWith('session-')).length,labs:c.filter(x=>x.startsWith('advanced-')).length}})}catch(e){res.status(500).json({error:'Could not calculate learning intelligence.'})}});
app.get('/api/recommendations',auth,async(req,res)=>{try{const c=Array.isArray(req.user.completed)?req.user.completed:[];const profiles=[
{name:'Phishing Awareness',session:2,lesson:2,lab:'advanced-phishing-investigation',labLabel:'Phishing Investigation',icon:'🎣',reason:'Strengthen your ability to spot manipulation, suspicious links and social-engineering signals.'},
{name:'Network Defense',session:6,lesson:6,lab:'advanced-network-attack-investigation',labLabel:'Network Attack Investigation',icon:'🌐',reason:'Build stronger traffic-analysis and defensive triage skills.'},
{name:'Cryptography',session:5,lesson:5,lab:null,labLabel:null,icon:'🔐',reason:'Reinforce encryption, hashing and digital-signature fundamentals.'},
{name:'SOC & Incident Response',session:6,lesson:11,lab:'advanced-soc-incident-response',labLabel:'SOC Incident Response',icon:'🚨',reason:'Improve alert correlation, triage and incident containment decisions.'},
{name:'Digital Forensics',session:10,lesson:10,lab:'advanced-digital-forensics-case',labLabel:'Digital Forensics Case',icon:'🔍',reason:'Practice evidence correlation, timelines and defensible preservation decisions.'},
{name:'Web Security',session:8,lesson:8,lab:'advanced-web-security-lab',labLabel:'Web Security Lab',icon:'🛡️',reason:'Strengthen secure application analysis, authorization and input-validation reasoning.'},
{name:'Identity & Access',session:3,lesson:3,lab:null,labLabel:null,icon:'🔑',reason:'Reinforce authentication, authorization, MFA and least-privilege concepts.'},
{name:'Malware Defense',session:4,lesson:4,lab:'advanced-ransomware-response',labLabel:'Ransomware Response',icon:'🦠',reason:'Practice containment and recovery decisions during a simulated malware incident.'}
];
const lessonMap={};profiles.forEach(p=>lessonMap[p.name]=p.lesson);const labMap={};profiles.forEach(p=>{if(p.lab)labMap[p.name]=p.lab});const scored=profiles.map(p=>{const lessonDone=c.includes('lesson-'+p.lesson),sessionDone=c.includes('session-'+p.session),labDone=p.lab?c.includes(p.lab):false;const score=(lessonDone?55:0)+(sessionDone?25:0)+(labDone?20:0);let actionType='session',actionTitle=`Cyber Session: ${p.name}`,actionDetail='Build the concept foundation before taking on the investigation.',action='openSession',actionArg=p.session,cta='START SESSION';if(!sessionDone){actionType='session';actionTitle=`Cyber Session: ${p.name}`;actionDetail='A focused refresher will raise this skill signal and prepare you for practice.';action='openSession';actionArg=p.session;cta='START SESSION'}else if(p.lab&&!labDone){actionType='lab';actionTitle=p.labLabel;actionDetail='You understand the basics. Now apply them in an evidence-based investigation.';action=p.lab==='advanced-digital-forensics-case'?'openForensicsLab':p.lab==='advanced-web-security-lab'?'openWebSecurityLab':'advancedLab';actionArg=p.lab==='advanced-digital-forensics-case'||p.lab==='advanced-web-security-lab'?null:p.lab.replace('advanced-','').replace(/-investigation|-/g,'');cta='OPEN LAB'}else{actionType='challenge';actionTitle=`Advanced ${p.name} Challenge`;actionDetail='Your foundation is strong. Keep progressing with a harder challenge.';action='challenges';actionArg=null;cta='VIEW CHALLENGES'}return {...p,score,lessonDone,sessionDone,labDone,actionType,actionTitle,actionDetail,action,actionArg,cta}}).sort((a,b)=>a.score-b.score);const focus=scored[0],strong=scored[scored.length-1];const completedCount=c.filter(x=>x.startsWith('lesson-')||x.startsWith('session-')||x.startsWith('advanced-')).length;res.json({focus,strong,items:scored.slice(0,4),completedCount,headline:focus.score<50?'FOUNDATION FOCUS':focus.score<80?'SKILL BOOST':'MASTERY STRETCH'});}catch(e){console.error('Recommendation error:',e);res.status(500).json({error:'Could not calculate adaptive recommendations.'})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const PORT = process.env.PORT || 10000;

init().then(() => {
  app.listen(PORT, "0.0.0.0", () => {
    console.log(`CYBER//QUEST online on 0.0.0.0:${PORT}`);
  });
}).catch(e => {
  console.error(e);
  process.exit(1);
});
